name: CI/CD Pipeline
on:
  push:
    branches:
      - sit
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Checkout payments-common-model
        uses: actions/checkout@v2
        with:
          repository: PapssAfrica/payments-common-model
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: payments-common-model
      - name: Install payments-common-model
        run: mvn clean install -DskipTests -f ./payments-common-model/pom.xml
          
      - name: Maven Package Corebanking adaptor
        run: mvn clean package -DskipTests -f ./pom.xml
        
        
  
